### PR TITLE
Conform to Polyglot Marking Guidelines for HTML

### PR DESCRIPTION
**Pull request by Oxymoron290**
Please see https://stackoverflow.com/questions/7020961/uppercase-or-lowercase-doctype

### CODE REVIEW

**Comment by hgehlhausen** [comment]
Thank you for your contribution, but the specification and link you cite both state it is case-insensitive.

**Comment by Oxymoron290** [comment]
image

**Comment by hgehlhausen** [comment]
https://www.w3.org/TR/html53/syntax.html#the-doctype

screenshot from 2018-03-13 20-53-00

**Comment by hgehlhausen** [comment]
Specifically an HTML5 app, but if it were going to some production environment, yes, DOCTYPE would be all capitalized.

Thanks again.

**Pull request closed without merging**
